### ISSUE TITLE
Wrong example for "GNU style" braces

### ISSUE THREAD

**Issue by Artoria2e5** [gnss-sdr/geniuss-place#1]
http://gnss-sdr.org/coding-style/#braces-should-follow-the-gnu-style seems to miss out indentation for curly braces relative to the statements.

The example posted uses:

```C++
void f(int a)
{
    int i;
    if (a > 0)
    {
        i = a;
    }
    else
    {
        i = a;
    }
}

class A
{
};
```

as opposed to:

```C++
void f(int a)
{
    int i;
    if (a > 0)
        {
            i = a;
        }
    else
        {
            i = a;
        }
}

class A
{
};
```
as described by GNU, the description and seen in gnss-sdr source code.

**Comment by Artoria2e5** [comment]
Running http://www.rosvall.ie/cgi-bin/genCodeStd.pl with GNU style gives the correct result. Weird.

**Comment by carlesfernandez** [comment]
Thank you for spotting this. This has been fixed in commit https://github.com/gnss-sdr/geniuss-place/commit/19448dcec03db95a0409bed1f180ecb26bd70acd and is now online at http://gnss-sdr.org/coding-style/#indentation-and-spacing
