### ISSUE TITLE
Link rot in RTL2832U tutorial page

### ISSUE THREAD

**Issue by acebrianjuan** [gnss-sdr/geniuss-place#10]
- Affected page: [GNSS-SDR operation with a Realtek RTL2832U USB dongle DVB-T receiver ](http://gnss-sdr.org/docs/tutorials/gnss-sdr-operation-realtek-rtl2832u-usb-dongle-dvb-t-receiver/)

- Description: The link pointing to Antti Palosaari's original thread is no longer available.

One possible solution would be to replace the [dead link](http://thread.gmane.org/gmane.linux.drivers.video-input-infrastructure/44461/focus=44461) with a [saved snapshot](https://web.archive.org/web/20180206165653/http://article.gmane.org/gmane.linux.drivers.video-input-infrastructure/44461) from the Internet Archive Wayback Machine.

**Comment by carlesfernandez** [comment]
Fixed, thank you.
