### ISSUE TITLE
Off-by-one-error in matlab/octave script + octave plotting issue

### ISSUE THREAD

**Issue by lenhart** [gnss-sdr/geniuss-place#51]
Hi, 

### off by one error
I found that the dimensions for the surface plot do not match [here](https://gnss-sdr.org/docs/sp-blocks/acquisition/#plotting-results-with-matlaboctave).
`f = -doppler_max:doppler_step:(doppler_max);`
f has size (doppler_max/doppler_step *2 )+1, whereas in the .m file the acq_grid has one less in the respective dimension.

My thoughts on that
case 1: error in matlab script/different specifications. in that case probably one boundary value or 0 should be excluded
case 2: error in .m file generation, dropping one line
case 3: error somewhere deeper in gnss-sdr (less likely)

Until I find the issue I probably have wasted much time and/or forgot about it, so I opened this issue and maybe you have thoughts about that.

### octave partial surface plot 

Strangely octave does not plot the full surface plot. 
![Screenshot at 2021-02-04 21-17-55](https://user-images.githubusercontent.com/29774930/106950473-bf441a00-672e-11eb-8b60-6ae47a6007ed.png)
left matlab, right octave, executing the same script (where I reduced f by one to have matching indices).
Min and max values for acq_grid are identical, so octave sees the whole structure.. I found possible different handling of NaN values searching the internet, but there are non in the data structure... 

For this plot I used the .m file generated from the first fix example. Other ones have the same issue though.
Do you think this is a problem with the script/file or rather in octave?

Cheers!

**Comment by carlesfernandez** [comment]
Hi @lenhart 

the off-by-one error in the website was fixed in 05239229c8eca5c7ca5ca4c372e0df2a023f651e I just forgot to mention it here, sorry about that.

To be honest, I have no idea what is causing the problem with the octave plot. I've reproduced that with Octave 6.2.0 and the plot seems right.
