### ISSUE TITLE
Incorrect inheritance hierarchy

### ISSUE THREAD

**Issue by jwmelto** [gnss-sdr/geniuss-place#71]
In [Fundamentals](https://gnss-sdr.org/docs/fundamentals/), it explicitly states that `GNSSBlockInterface` inherits from `gr::top_block`. This is wrong. 

`GNSSBlockInterface` has no base classes. 

Furthermore, nothing in GNSS-SDR derives from `gr::top_block`. Although in GNU Radio python application, it is common to inherit from `gr.top_block`, GNSS-SDR uses aggregation rather than inheritance for managing the flowgraph.

**Comment by carlesfernandez** [comment]
You are right, I need to change that!

**Comment by carlesfernandez** [comment]
Should be fixed now. Thanks for spotting this issue!
