### ISSUE TITLE
Possible typo in file extension

### ISSUE THREAD

**Issue by acebrianjuan** [gnss-sdr/geniuss-place#8]
This is a minor issue but it could lead to confusion:

The example for [`Two_Bit_Packed_File_Signal_Source`](http://gnss-sdr.org/docs/sp-blocks/signal-source/#implementation-two_bit_packed_file_signal_source) contains the following line:

    SignalSource.filename=/data/my_capture.datz

I think the file extension should be **`.dat`** instead of **`.datz`**

**Comment by carlesfernandez** [comment]
Fixed. Thanks for spotting it.
